# Amount of attempts to login with the wrong password before the player is kicked.
password_attempts: 3
# Allow OPs to force other OPs to logout or change their password.
op_vs_op: false
# Ban duration in seconds, for when a player runs out of attempts.
# Set to 0 for instant unban. Set to -1 to ban permanently.
ban_duration: 300

# Uncomment the following lines to enable a custom location to send the unauthenticated players to.
# The default location is the spawn point.

# unauthenticated_location:
#  world: world
#  x: 0
#  y: 64
#  z: 0
#  yaw: 0
#  pitch: 0