# Amount of attempts to login with the wrong password before the player is kicked.
password_attempts: 3
# Allow OPs to force other OPs to logout or change their password.
op_vs_op: false

# Uncomment the following lines to enable a custom location to send the unauthenticated players to.
# The default location is the spawn point.

# unauthenticated_location:
#  world: world
#  x: 0
#  y: 64
#  z: 0
#  yaw: 0
#  pitch: 0