name: SecurityPL3
version: '${project.version}'
main: code.blurone.securitypl3.SecurityPL3
api-version: '1.20'
load: STARTUP
author: 'BlurOne!'
website: 'https://github.com/BlurOne-GIT/SecurityPL3'
description: 'Another minecraft authentication plugin (for the third time).'
commands:
  logout:
    description: 'Logout from the server.'
    usage: '/logout'
  changepassword:
    description: 'Change your password.'
    usage: '/changepassword'
  forcelogout:
    description: '(Admin) Force a player to logout.'
    usage: '/forcelogout <player>'
    permission: 'securitypl3.admin'
  forcechangepassword:
    description: '(Admin) Force a player to change their password.'
    usage: '/forcechangepassword <player>'
    permission: 'securitypl3.admin'
